#:schema node_modules/wrangler/config-schema.json
name = "personal-site"
compatibility_date = "2024-06-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./dist"

[vars]
API_HOST = "bcox.dev"
PAGE_TITLE = "bcox"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "PERSONAL_BUCKET"
bucket_name = "personal-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"